export const Types = {
    // Comment
    UPDATE_ITEM_DATAES: "UPDATE_ITEM_DATAES",
    
    // Login
    CHANGE_LOGIN_TABLE_STATE: "CHANGE_LOGIN_TABLE_STATE",
    UPDATE_USER_INFO: "UPDATE_USER_INFO",
    LOGIN_OUT: "LOGIN_OUT",
    // Sort
    SORT_STATE_CHANGE: "SORT_STATE_CHANGE",

    // AlertPlane
    POP_ALERT_PLANE: "POP_ALERT_PLANE",

    // HandleData
    UPDATE_GLOBAL_DATA_INFO: "UPDATE_GLOBAL_DATA_INFO"
}
